MODEL:
  NUM_CLASSES: 21
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("clipart_train", "clipart_test", "clipart_traintest")
SOLVER:
# 1e-3 for 40k iter, then continue with 1e-4 and 1e-5 for 10k iter each (total 60k iterations)
  MAX_ITER: 60000
  LR_STEPS: [40000, 50000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-4

OUTPUT_DIR: 'outputs/setup_3'
